org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-25.0.2.10-hotspot

minecraft_version=26.2
loader_version=0.18.4
fabric_version=0.159.0+26.2
loom_version=1.15.5
mod_version=1.0.1
maven_group=com.cooper
archives_base_name=server-reset-on-any-player-death
